//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASEGURADO
    {
        public ASEGURADO()
        {
            this.EXPEDIENTE = new HashSet<EXPEDIENTE>();
            this.POLIZA_VEHICULAR = new HashSet<POLIZA_VEHICULAR>();
        }
    
        public int Co_Asegurado { get; set; }
        public string Nu_DocumentoIdentidad { get; set; }
        public string No_Asegurado { get; set; }
        public string No_ApePaterno { get; set; }
        public string No_ApeMaterno { get; set; }
        public string Fl_Sexo { get; set; }
        public System.DateTime Fe_Nacimiento { get; set; }
        public string Tx_EstadoCivil { get; set; }
        public string Tx_Direccion { get; set; }
        public int Co_Distrito { get; set; }
        public string Tx_Correo { get; set; }
        public string Nu_Telefono1 { get; set; }
        public string Nu_Telefono2 { get; set; }
        public string Nu_Movil { get; set; }
        public string Tx_CentroTrabajo { get; set; }
        public string Tx_DireccionTrabajo { get; set; }
        public string Tx_CargoTrabajo { get; set; }
        public string Tx_Estado { get; set; }
    
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual ICollection<EXPEDIENTE> EXPEDIENTE { get; set; }
        public virtual ICollection<POLIZA_VEHICULAR> POLIZA_VEHICULAR { get; set; }
    }
}
