//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFICIARIO
    {
        public BENEFICIARIO()
        {
            this.EXPEDIENTE = new HashSet<EXPEDIENTE>();
        }
    
        public int Co_Beneficiario { get; set; }
        public string Nu_DocIdentidad { get; set; }
        public string No_Beneficiario { get; set; }
        public string No_ApePaterno { get; set; }
        public string No_ApeMaterno { get; set; }
        public string Fl_Sexo { get; set; }
        public System.DateTime Fe_Nacimiento { get; set; }
        public string Tx_EstadoCivil { get; set; }
        public string Tx_Direccion { get; set; }
        public string Tx_Correo { get; set; }
        public string Nu_Telefono1 { get; set; }
        public string Nu_Telefono2 { get; set; }
        public string Nu_Movil { get; set; }
        public string Tx_TipoParentesco { get; set; }
        public decimal Po_Capital { get; set; }
        public string Fl_Estado { get; set; }
    
        public virtual ICollection<EXPEDIENTE> EXPEDIENTE { get; set; }
    }
}
