//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTA_NOTARIAL
    {
        public int Co_NumCartaNotarial { get; set; }
        public string Tx_Descripción { get; set; }
        public Nullable<System.DateTime> Fe_Creación { get; set; }
        public Nullable<System.DateTime> Fe_Emision { get; set; }
        public Nullable<System.DateTime> Fe_Recepcion { get; set; }
        public int Co_NumInfProc { get; set; }
    
        public virtual INFORME_PROCURADORIA INFORME_PROCURADORIA { get; set; }
    }
}
