//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERT_MEDICO_DEFUNCION
    {
        public int Co_Folio { get; set; }
        public string Tx_Circunscripcion { get; set; }
        public string Nu_Anio { get; set; }
        public string Tx_LugarDefuncion { get; set; }
        public string Tx_CausaMuerte { get; set; }
        public Nullable<System.DateTime> Fe_Emision { get; set; }
        public string Tx_FirmadoPor { get; set; }
        public int Co_Distrito { get; set; }
        public string Nu_Siniestro { get; set; }
        public int Co_Expediente { get; set; }
    
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual EXPEDIENTE EXPEDIENTE { get; set; }
    }
}
