//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRITERIO_EVALUACION
    {
        public CRITERIO_EVALUACION()
        {
            this.EVALUACION_PRESTADORA = new HashSet<EVALUACION_PRESTADORA>();
        }
    
        public int Co_Criterio { get; set; }
        public string No_Criterio { get; set; }
        public string Tx_Descripcion { get; set; }
        public decimal Po_Peso { get; set; }
    
        public virtual ICollection<EVALUACION_PRESTADORA> EVALUACION_PRESTADORA { get; set; }
    }
}
