//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO
    {
        public DEPARTAMENTO()
        {
            this.PROVINCIA = new HashSet<PROVINCIA>();
        }
    
        public int Co_Departamento { get; set; }
        public string No_Departamento { get; set; }
    
        public virtual ICollection<PROVINCIA> PROVINCIA { get; set; }
    }
}
