//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRITO
    {
        public DISTRITO()
        {
            this.ASEGURADO = new HashSet<ASEGURADO>();
            this.CERT_MEDICO_DEFUNCION = new HashSet<CERT_MEDICO_DEFUNCION>();
            this.EMPLEADO = new HashSet<EMPLEADO>();
            this.PRESTADORA = new HashSet<PRESTADORA>();
            this.PROT_JURADA_DOMICILIO = new HashSet<PROT_JURADA_DOMICILIO>();
            this.SEDE = new HashSet<SEDE>();
        }
    
        public int Co_Distrito { get; set; }
        public string No_Distrito { get; set; }
        public int Co_Provincia { get; set; }
    
        public virtual ICollection<ASEGURADO> ASEGURADO { get; set; }
        public virtual ICollection<CERT_MEDICO_DEFUNCION> CERT_MEDICO_DEFUNCION { get; set; }
        public virtual PROVINCIA PROVINCIA { get; set; }
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
        public virtual ICollection<PRESTADORA> PRESTADORA { get; set; }
        public virtual ICollection<PROT_JURADA_DOMICILIO> PROT_JURADA_DOMICILIO { get; set; }
        public virtual ICollection<SEDE> SEDE { get; set; }
    }
}
