//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.SOLICITUD_AFILIACION = new HashSet<SOLICITUD_AFILIACION>();
            this.SOLICITUD_AFILIACION1 = new HashSet<SOLICITUD_AFILIACION>();
        }
    
        public int Co_Empleado { get; set; }
        public string No_Empleado { get; set; }
        public string No_ApePaterno { get; set; }
        public string No_ApeMaterno { get; set; }
        public string No_EmpleadoCompleto { get; set; }
        public string Nu_Dni { get; set; }
        public int Fl_Sexo { get; set; }
        public System.DateTime Fe_Nacimiento { get; set; }
        public string Nu_Telefono { get; set; }
        public string Nu_Movil { get; set; }
        public string Tx_Direccion { get; set; }
        public int Co_Distrito { get; set; }
        public string Tx_Correo { get; set; }
        public int Co_Cargo { get; set; }
        public System.DateTime Fe_RegistroIns { get; set; }
        public string No_UsuarioIns { get; set; }
        public System.DateTime Fe_RegistroUpd { get; set; }
        public string No_UsuarioUpd { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual ICollection<SOLICITUD_AFILIACION> SOLICITUD_AFILIACION { get; set; }
        public virtual ICollection<SOLICITUD_AFILIACION> SOLICITUD_AFILIACION1 { get; set; }
    }
}
