//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIALIDAD
    {
        public ESPECIALIDAD()
        {
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public int Co_Especialidad { get; set; }
        public string No_Especialidad { get; set; }
    
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
