//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_SINIESTRO
    {
        public ESTADO_SINIESTRO()
        {
            this.SINIESTRO = new HashSet<SINIESTRO>();
        }
    
        public int Co_EstadoSiniestro { get; set; }
        public string No_EstadoSiniestro { get; set; }
    
        public virtual ICollection<SINIESTRO> SINIESTRO { get; set; }
    }
}
