//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPEDIENTE
    {
        public EXPEDIENTE()
        {
            this.CERT_MEDICO_DEFUNCION = new HashSet<CERT_MEDICO_DEFUNCION>();
            this.HISTORIAL_CLINICO = new HashSet<HISTORIAL_CLINICO>();
            this.INFORME_INSPECTORIA = new HashSet<INFORME_INSPECTORIA>();
            this.INFORME_JUNTA_MEDICA = new HashSet<INFORME_JUNTA_MEDICA>();
            this.INFORME_PROCURADORIA = new HashSet<INFORME_PROCURADORIA>();
            this.POLIZA_VIDA = new HashSet<POLIZA_VIDA>();
            this.PROT_JURADA_DOMICILIO = new HashSet<PROT_JURADA_DOMICILIO>();
        }
    
        public int Co_Expediente { get; set; }
        public Nullable<int> Co_Asegurado { get; set; }
        public int Co_Beneficiario { get; set; }
    
        public virtual ASEGURADO ASEGURADO { get; set; }
        public virtual BENEFICIARIO BENEFICIARIO { get; set; }
        public virtual ICollection<CERT_MEDICO_DEFUNCION> CERT_MEDICO_DEFUNCION { get; set; }
        public virtual ICollection<HISTORIAL_CLINICO> HISTORIAL_CLINICO { get; set; }
        public virtual ICollection<INFORME_INSPECTORIA> INFORME_INSPECTORIA { get; set; }
        public virtual ICollection<INFORME_JUNTA_MEDICA> INFORME_JUNTA_MEDICA { get; set; }
        public virtual ICollection<INFORME_PROCURADORIA> INFORME_PROCURADORIA { get; set; }
        public virtual ICollection<POLIZA_VIDA> POLIZA_VIDA { get; set; }
        public virtual ICollection<PROT_JURADA_DOMICILIO> PROT_JURADA_DOMICILIO { get; set; }
    }
}
