//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMA_PAGO
    {
        public FORMA_PAGO()
        {
            this.POLIZA_VIDA = new HashSet<POLIZA_VIDA>();
            this.PRESUPUESTO = new HashSet<PRESUPUESTO>();
        }
    
        public int Co_FormaPago { get; set; }
        public string No_FormaPago { get; set; }
    
        public virtual ICollection<POLIZA_VIDA> POLIZA_VIDA { get; set; }
        public virtual ICollection<PRESUPUESTO> PRESUPUESTO { get; set; }
    }
}
