//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORME_INSPECTORIA
    {
        public int Co_NumInfInspect { get; set; }
        public Nullable<byte> Fl_IndiciosDolo { get; set; }
        public string Tx_Conclusiones { get; set; }
        public Nullable<byte> Fl_DocAnali { get; set; }
        public string Tx_DocsObs { get; set; }
        public Nullable<System.DateTime> Fe_Emision { get; set; }
        public string Tx_Resultados { get; set; }
        public Nullable<int> Co_Expediente { get; set; }
    
        public virtual EXPEDIENTE EXPEDIENTE { get; set; }
    }
}
