//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORME_ACCIDENTE_VEHICULAR
    {
        public INFORME_ACCIDENTE_VEHICULAR()
        {
            this.DOCUMENTO_INFORME_ACCIDENTE_VEHICULAR = new HashSet<DOCUMENTO_INFORME_ACCIDENTE_VEHICULAR>();
        }
    
        public int Co_InformeAccidenteVehicular { get; set; }
        public int Co_Siniestro { get; set; }
        public Nullable<System.DateTime> Fe_InformeAccidentVehicular { get; set; }
        public string Tx_Direccion { get; set; }
        public int Co_Distrito { get; set; }
        public string Tx_DanosProducidos { get; set; }
    
        public virtual ICollection<DOCUMENTO_INFORME_ACCIDENTE_VEHICULAR> DOCUMENTO_INFORME_ACCIDENTE_VEHICULAR { get; set; }
        public virtual SINIESTRO SINIESTRO { get; set; }
    }
}
