//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVITACION
    {
        public INVITACION()
        {
            this.SOLICITUD_AFILIACION = new HashSet<SOLICITUD_AFILIACION>();
        }
    
        public int Co_Invitacion { get; set; }
        public System.DateTime Fe_Invitacion { get; set; }
        public System.DateTime Fe_Expiracion { get; set; }
        public int Fl_Estado { get; set; }
        public System.DateTime Fe_RegistroIns { get; set; }
        public string No_UsuarioIns { get; set; }
        public System.DateTime Fe_RegistroUpd { get; set; }
        public string No_UsuarioUpd { get; set; }
    
        public virtual ICollection<SOLICITUD_AFILIACION> SOLICITUD_AFILIACION { get; set; }
    }
}
