//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIQUIDACION_VEHICULAR
    {
        public int Co_LiquidacionVehicular { get; set; }
        public int Co_Siniestro { get; set; }
        public string Tx_Observaciones { get; set; }
        public string Tx_Estado { get; set; }
        public int Co_Usuario { get; set; }
        public System.DateTime Fe_Registro { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual SINIESTRO SINIESTRO { get; set; }
    }
}
