//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARCA_VEHICULO
    {
        public MARCA_VEHICULO()
        {
            this.MODELO_VEHICULO = new HashSet<MODELO_VEHICULO>();
        }
    
        public int Co_MarcaVehiculo { get; set; }
        public string No_MarcaVehiculo { get; set; }
    
        public virtual ICollection<MODELO_VEHICULO> MODELO_VEHICULO { get; set; }
    }
}
