//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTOR_VEHICULO
    {
        public MOTOR_VEHICULO()
        {
            this.VEHICULO = new HashSet<VEHICULO>();
        }
    
        public int Co_MotorVehiculo { get; set; }
        public string No_MotorVehiculo { get; set; }
    
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
    }
}
