//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PACIFICOEntities : DbContext
    {
        public PACIFICOEntities()
            : base("name=PACIFICOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ARTICULO> ARTICULO { get; set; }
        public DbSet<ASEGURADO> ASEGURADO { get; set; }
        public DbSet<BENEFICIARIO> BENEFICIARIO { get; set; }
        public DbSet<CARGO> CARGO { get; set; }
        public DbSet<CARTA_NOTARIAL> CARTA_NOTARIAL { get; set; }
        public DbSet<CERT_MEDICO_DEFUNCION> CERT_MEDICO_DEFUNCION { get; set; }
        public DbSet<CRITERIO_EVALUACION> CRITERIO_EVALUACION { get; set; }
        public DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public DbSet<DISTRITO> DISTRITO { get; set; }
        public DbSet<DOCUMENTO_INFORME_ACCIDENTE_VEHICULAR> DOCUMENTO_INFORME_ACCIDENTE_VEHICULAR { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<ESPECIALIDAD> ESPECIALIDAD { get; set; }
        public DbSet<ESTADO_SINIESTRO> ESTADO_SINIESTRO { get; set; }
        public DbSet<ESTADO_SOLICITUD> ESTADO_SOLICITUD { get; set; }
        public DbSet<EVALUACION_PRESTADORA> EVALUACION_PRESTADORA { get; set; }
        public DbSet<EXPEDIENTE> EXPEDIENTE { get; set; }
        public DbSet<FORMA_PAGO> FORMA_PAGO { get; set; }
        public DbSet<HISTORIAL_CLINICO> HISTORIAL_CLINICO { get; set; }
        public DbSet<INFORME_ACCIDENTE_VEHICULAR> INFORME_ACCIDENTE_VEHICULAR { get; set; }
        public DbSet<INFORME_INSPECTORIA> INFORME_INSPECTORIA { get; set; }
        public DbSet<INFORME_PROCURADORIA> INFORME_PROCURADORIA { get; set; }
        public DbSet<INVITACION> INVITACION { get; set; }
        public DbSet<LIQUIDACION_VEHICULAR> LIQUIDACION_VEHICULAR { get; set; }
        public DbSet<MARCA_VEHICULO> MARCA_VEHICULO { get; set; }
        public DbSet<MODELO_VEHICULO> MODELO_VEHICULO { get; set; }
        public DbSet<MOTOR_VEHICULO> MOTOR_VEHICULO { get; set; }
        public DbSet<ORDEN_REPARACION> ORDEN_REPARACION { get; set; }
        public DbSet<POLIZA_VEHICULAR> POLIZA_VEHICULAR { get; set; }
        public DbSet<POLIZA_VIDA> POLIZA_VIDA { get; set; }
        public DbSet<PRESTADORA> PRESTADORA { get; set; }
        public DbSet<PRESUPUESTO> PRESUPUESTO { get; set; }
        public DbSet<PRESUPUESTO_DETALLE> PRESUPUESTO_DETALLE { get; set; }
        public DbSet<PROCURADOR> PROCURADOR { get; set; }
        public DbSet<PROT_JURADA_DOMICILIO> PROT_JURADA_DOMICILIO { get; set; }
        public DbSet<PROVINCIA> PROVINCIA { get; set; }
        public DbSet<RED> RED { get; set; }
        public DbSet<REGISTRO_DOCUMENTO> REGISTRO_DOCUMENTO { get; set; }
        public DbSet<SEDE> SEDE { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<SERVICIO_SEDE> SERVICIO_SEDE { get; set; }
        public DbSet<SINIESTRO> SINIESTRO { get; set; }
        public DbSet<SOLICITUD_AFILIACION> SOLICITUD_AFILIACION { get; set; }
        public DbSet<TIPO_POLIZA_VEHICULAR> TIPO_POLIZA_VEHICULAR { get; set; }
        public DbSet<TIPO_SINIESTRO> TIPO_SINIESTRO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VEHICULO> VEHICULO { get; set; }
    }
}
