//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLIZA_VEHICULAR
    {
        public POLIZA_VEHICULAR()
        {
            this.REGISTRO_DOCUMENTO = new HashSet<REGISTRO_DOCUMENTO>();
            this.SINIESTRO = new HashSet<SINIESTRO>();
        }
    
        public int Co_PolizaVehicular { get; set; }
        public string Nu_PolizaVehicular { get; set; }
        public System.DateTime Fe_Inicio { get; set; }
        public Nullable<System.DateTime> Fe_Fin { get; set; }
        public Nullable<decimal> Ss_MontoCobertura { get; set; }
        public int Co_Asegurado { get; set; }
        public int Co_TipoPolizaVehicular { get; set; }
        public int Co_Vehiculo { get; set; }
    
        public virtual ASEGURADO ASEGURADO { get; set; }
        public virtual TIPO_POLIZA_VEHICULAR TIPO_POLIZA_VEHICULAR { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
        public virtual ICollection<REGISTRO_DOCUMENTO> REGISTRO_DOCUMENTO { get; set; }
        public virtual ICollection<SINIESTRO> SINIESTRO { get; set; }
    }
}
