//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLIZA_VIDA
    {
        public int Co_PolizaVida { get; set; }
        public decimal Ss_Prima { get; set; }
        public System.DateTime Fe_Creacion { get; set; }
        public System.DateTime Fe_Renovacion { get; set; }
        public System.DateTime Fe_Vencimiento { get; set; }
        public System.DateTime Fe_InicioVigencia { get; set; }
        public int Co_FormaPago { get; set; }
        public string Fl_Estado { get; set; }
        public string Nu_DocIndentidadCliente { get; set; }
        public string Nu_DocIndentidadBeneficiario { get; set; }
        public string Tx_RutaFoto { get; set; }
        public int Co_Expediente { get; set; }
    
        public virtual EXPEDIENTE EXPEDIENTE { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
    }
}
