//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTO_DETALLE
    {
        public int Co_Presupuesto { get; set; }
        public int Co_Articulo { get; set; }
        public Nullable<int> Qt_Cantidad { get; set; }
        public Nullable<decimal> Ss_PrecioDetalle { get; set; }
        public Nullable<decimal> Ss_Descuento { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual PRESUPUESTO PRESUPUESTO { get; set; }
    }
}
