//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTO
    {
        public PRESUPUESTO()
        {
            this.ORDEN_REPARACION = new HashSet<ORDEN_REPARACION>();
            this.PRESUPUESTO_DETALLE = new HashSet<PRESUPUESTO_DETALLE>();
        }
    
        public int Co_Presupuesto { get; set; }
        public string Nu_Presupuesto { get; set; }
        public Nullable<System.DateTime> Fe_Presupuesto { get; set; }
        public int Co_FormaPago { get; set; }
        public Nullable<byte> Fl_Estado { get; set; }
        public string Tx_Observacion { get; set; }
        public int Co_Siniestro { get; set; }
    
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        public virtual ICollection<ORDEN_REPARACION> ORDEN_REPARACION { get; set; }
        public virtual SINIESTRO SINIESTRO { get; set; }
        public virtual ICollection<PRESUPUESTO_DETALLE> PRESUPUESTO_DETALLE { get; set; }
    }
}
