//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROT_JURADA_DOMICILIO
    {
        public int Co_Protocolo { get; set; }
        public string Tx_Direccion { get; set; }
        public System.DateTime Fe_Celebreacion { get; set; }
        public int Co_Distrito { get; set; }
        public string Nu_Siniestro { get; set; }
        public int Co_Expediente { get; set; }
    
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual EXPEDIENTE EXPEDIENTE { get; set; }
    }
}
