//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVINCIA
    {
        public PROVINCIA()
        {
            this.DISTRITO = new HashSet<DISTRITO>();
        }
    
        public int Co_Provincia { get; set; }
        public string No_Provincia { get; set; }
        public int Co_Departamento { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual ICollection<DISTRITO> DISTRITO { get; set; }
    }
}
