//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RED
    {
        public RED()
        {
            this.SERVICIO_SEDE = new HashSet<SERVICIO_SEDE>();
        }
    
        public int Co_Red { get; set; }
        public string No_Red { get; set; }
    
        public virtual ICollection<SERVICIO_SEDE> SERVICIO_SEDE { get; set; }
    }
}
