//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_DOCUMENTO
    {
        public int Co_RegistroDoc { get; set; }
        public string Nu_RegistroDoc { get; set; }
        public int Co_PolizaVehicular { get; set; }
        public string Tx_Descripcion { get; set; }
        public Nullable<byte> Fl_Estado { get; set; }
        public Nullable<System.DateTime> Fe_Registro { get; set; }
    
        public virtual POLIZA_VEHICULAR POLIZA_VEHICULAR { get; set; }
    }
}
