//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.SERVICIO_SEDE = new HashSet<SERVICIO_SEDE>();
        }
    
        public int Co_Servicio { get; set; }
        public string No_Servicio { get; set; }
        public string Tx_Descripcion { get; set; }
        public int Co_Especialidad { get; set; }
    
        public virtual ESPECIALIDAD ESPECIALIDAD { get; set; }
        public virtual ICollection<SERVICIO_SEDE> SERVICIO_SEDE { get; set; }
    }
}
