//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINIESTRO_VEHICULAR
    {
        public int Co_Siniestro { get; set; }
        public string No_Asegurado { get; set; }
        public string Nu_Placa { get; set; }
        public string Nu_PolizaVehicular { get; set; }
    }
}
