//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_POLIZA_VEHICULAR
    {
        public TIPO_POLIZA_VEHICULAR()
        {
            this.POLIZA_VEHICULAR = new HashSet<POLIZA_VEHICULAR>();
        }
    
        public int Co_TipoPolizaVehicular { get; set; }
        public string No_TipoPolizaVehicular { get; set; }
    
        public virtual ICollection<POLIZA_VEHICULAR> POLIZA_VEHICULAR { get; set; }
    }
}
