//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public VEHICULO()
        {
            this.POLIZA_VEHICULAR = new HashSet<POLIZA_VEHICULAR>();
        }
    
        public int Co_Vehiculo { get; set; }
        public string Nu_Placa { get; set; }
        public int Co_ModeloVehiculo { get; set; }
        public int Co_MotorVehiculo { get; set; }
        public string Tx_DescripcionChasis { get; set; }
    
        public virtual MODELO_VEHICULO MODELO_VEHICULO { get; set; }
        public virtual MOTOR_VEHICULO MOTOR_VEHICULO { get; set; }
        public virtual ICollection<POLIZA_VEHICULAR> POLIZA_VEHICULAR { get; set; }
    }
}
